### ISSUE TITLE
Exception renderer IndexOutOfRangeException

### ISSUE THREAD

**Issue by daningalla** [verticalsoftware/vertical-spectreconsolelogger#21]
```
Index was outside the bounds of the array.
   at Vertical.SpectreLogger.Rendering.ExceptionRenderer.PrintParameters(IWriteBuffer buffer, LogLevelProfile profile, Group signatureGroup, Options options) in C:\Users\dan\Dev\vertical\vertical-spectreconsolelogger\src\Rendering\ExceptionRenderer.cs:line 210
   at Vertical.SpectreLogger.Rendering.ExceptionRenderer.<>c__DisplayClass5_0.<PrintStackFrame>b__0(String method) in C:\Users\dan\Dev\vertical\vertical-spectreconsolelogger\src\Rendering\ExceptionRenderer.cs:line 166
   at Vertical.SpectreLogger.Output.WriteBufferExtensions.WriteLogValue[T](IWriteBuffer buffer, LogLevelProfile profile, TemplateSegment templateSegment, T value, Action`1 writer) in C:\Users\dan\Dev\vertical\vertical-spectreconsolelogger\src\Output\WriteBufferExtensions.cs:line 112
   at Vertical.SpectreLogger.Rendering.ExceptionRenderer.PrintStackFrame(IWriteBuffer buffer, LogLevelProfile profile, String frame, Options options) in C:\Users\dan\Dev\vertical\vertical-spectreconsolelogger\src\Rendering\ExceptionRenderer.cs:line 157
   at Vertical.SpectreLogger.Rendering.ExceptionRenderer.PrintStackTrace(IWriteBuffer buffer, LogLevelProfile profile, Exception exception, Options options) in C:\Users\dan\Dev\vertical\vertical-spectreconsolelogger\src\Rendering\ExceptionRenderer.cs:line 124
   at Vertical.SpectreLogger.Rendering.ExceptionRenderer.Render(IWriteBuffer buffer, LogEventContext& context) in C:\Users\dan\Dev\vertical\vertical-spectreconsolelogger\src\Rendering\ExceptionRenderer.cs:line 72
   at Vertical.SpectreLogger.Rendering.ExceptionRenderer.Vertical.SpectreLogger.Core.ITemplateRenderer.Render(IWriteBuffer buffer, LogEventContext& context)
   at Vertical.SpectreLogger.Rendering.RendererPipeline.Render(LogEventContext& logEventContext) in C:\Users\dan\Dev\vertical\vertical-spectreconsolelogger\src\Rendering\RendererPipeline.cs:line 54
   at Vertical.SpectreLogger.Rendering.RendererPipeline.Vertical.SpectreLogger.Core.IRendererPipeline.Render(LogEventContext& logEventContext)
   at Vertical.SpectreLogger.SpectreLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\Users\dan\Dev\vertical\vertical-spectreconsolelogger\src\SpectreLogger.cs:line 61
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
```

Parameters not being parsed correctly

**Comment by daningalla** [comment]
Parser is not handling signatures that don't have parameter names, e.g.:

```
   at MessagePack.Resolvers.DynamicObjectResolverAllowPrivate.GetFormatter[T]()
   at MessagePack.Resolvers.ContractlessStandardResolverAllowPrivate.FormatterCache`1..cctor()
--- End of stack trace from previous location ---
   at MessagePack.FormatterResolverExtensions.Throw(TypeInitializationException ex)
   >> at MessagePack.Formatters.SharpGraphDb_Client_Messages_RequestFormatter1.Serialize(MessagePackWriter& , Request , MessagePackSerializerOptions )
   >> at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
```
