### ISSUE TITLE
NullReferenceException in Vertical.SpectreLogger.Templates

### ISSUE THREAD

**Issue by daningalla** [verticalsoftware/vertical-spectreconsolelogger#26]
From #25 reported by @duggaraju

Unhandled exception. System.AggregateException: An error occurred while writing to logger(s). (Object reference not set to an instance of an object.)
---> System.NullReferenceException: Object reference not set to an instance of an object.
at Vertical.SpectreLogger.Templates.TemplateSegment.get_CompositeFormatSpan()
at Vertical.SpectreLogger.Output.WriteBufferExtensions.WriteLogValue[T](IWriteBuffer buffer, LogLevelProfile profile, TemplateSegment templateSegment, T value, Action1 writer) at Vertical.SpectreLogger.Rendering.RendererPipeline.Render(LogEventContext& logEventContext) at Vertical.SpectreLogger.SpectreLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func3 formatter)
at Microsoft.Extensions.Logging.Logger.g__LoggerLog|13_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func3 formatter, List1& exceptions, TState& state)
--- End of inner exception stack trace ---
at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List1 exceptions) at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func3 formatter)
at Microsoft.Extensions.Logging.Logger1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func3 formatter)
at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, String message, Object[] args)

**Comment by duggaraju** [comment]
This was the simplest code I was able to repro the issue.

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Vertical.SpectreLogger;

var collection = new ServiceCollection();
collection.AddLogging(builder => builder.AddSpectreConsole());
var provider = collection.BuildServiceProvider();
var logger = provider.GetRequiredService<ILogger<Program>>();

var exception = new NotSupportedException("Some randome exception");

await Task.WhenAll(Enumerable.Range(0, 20).Select(async i => {
    await Task.Delay(500);
    try
    {
        throw exception;
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Try log an error message {i}", i);
    }
}));


Markup error: Encountered malformed markup tag at position 18.
Markup error: Encountered malformed markup tag at position 18.
[9:27:49 AM Fail] Try log an error message 7
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[9:27:49 AM Fail] Try log an error message 19
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[9:27:49 AM Fail] Try log an error message 8
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[9:27:49 AM Fail] Try log an error message 5
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[9:27:49 AM Fail] Try log an error message 9
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[9:27:49 AM Fail] Try log an error message 6
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[9:27:49 AM Fail] Try log an error message 12
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[9:27:49 AM Fail] Try log an error message 11
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[9:27:49 AM Fail] Try log an error message 1
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
Tried to write:
[9:27:50 AM Fail] Try log an error message 15
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[9:27:50 AM Fail] Try log an error message 2
System.NotSupportedException: Some randome exception
[9:27:50 AM Fail] Try log an error message 13
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[grey85][[[grey85]
[9:27:50 AM Fail] Try log an error message 3
System.NotSupportedException: Some randome exception
[9:27:50 AM Fail] Try log an error message 18
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
Tried to write:
[9:27:50 AM Fail] Try log an error message 0
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[grey85][[[grey85]
[9:27:50 AM Fail] Try log an error message 16
System.NotSupportedException: Some randome exception
[9:27:50 AM Fail] Try log an error message 14
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
[9:27:49 AM Fail] Try log an error message 4
System.NotSupportedException: Some randome exception
   at <<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 19
Unhandled exception. System.AggregateException: An error occurred while writing to logger(s). (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Vertical.SpectreLogger.Templates.TemplateSegment.get_CompositeFormatSpan()
   at Vertical.SpectreLogger.Output.WriteBufferExtensions.WriteLogValue[T](IWriteBuffer buffer, LogLevelProfile profile, TemplateSegment templateSegment, T value, Action`1 writer)
   at Vertical.SpectreLogger.Rendering.DateTimeRenderer.Render(IWriteBuffer buffer, LogEventContext& context)
   at Vertical.SpectreLogger.Rendering.RendererPipeline.Render(LogEventContext& logEventContext)
   at Vertical.SpectreLogger.SpectreLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, Exception exception, String message, Object[] args)
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__1>d.MoveNext() in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 23
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in C:\Users\krishndu\source\repos\ConsoleTest\ConsoleTest\Program.cs:line 15
   at Program.<Main>(String[] args)


The trick was the Task.Delay() to ensure it would await and run later.
I also see markup errors because of mismatched [ brackets

**Comment by duggaraju** [comment]
Doesn't repro every time but easily  1 in 5 I can repro this.  My theory is that RegEx.Match is doing a delayed evaluation and is not thread safe but haven't digged in to the MSDN docs yet.

**Comment by duggaraju** [comment]
If I change the TemplateSegment class to do the match expansion in the constructor i don't have the issue.

class TemplateSegment
{
  public TemplateSegment(Match? match,...)
  {
     CompositeFormatSpan = match?.Groups[CompositeFormatSpanGroup].Value;
  }

  private string? CompositeFormatSpan { get; }
}

From microsoft documentation:
https://learn.microsoft.com/en-us/dotnet/standard/base-types/thread-safety-in-regular-expressions
However, result objects (Match and MatchCollection) returned by Regex should be used on a single thread. Although many of these objects are logically immutable, their implementations could delay computation of some results to improve performance, and as a result, callers must serialize access to them.

**Comment by daningalla** [comment]
This is extremely helpful @duggaraju, thank you! I will get into this tonight.

**Comment by daningalla** [comment]
@duggaraju - a new pre-release package will be up on NuGet shortly. Let me know if the issue still occurs.

**Comment by duggaraju** [comment]
I tried 0.10.1-dev.20230711.18 of the package and can still repro the issue.   am I missing something?

**Comment by daningalla** [comment]
Hmm, with the change I made I cannot repro now, but I will begin tweaking the parameters of the repro project and see if I can't get it to misbehave again.

**Comment by duggaraju** [comment]
I was able to repro this on the sample bug-repro/MultiThreaded  but changing the delay to Task.Delay(25) 

Just calling _match.Groups creates a GroupCollection object but doesn't evaluate anything.  The right thing to be thread safe is to get the values in the constructor instead of getter.

**Comment by daningalla** [comment]
Implementing...

**Comment by daningalla** [comment]
@duggaraju - can you grab latest and experiment with the [MultiThreaded](https://github.com/verticalsoftware/vertical-spectreconsolelogger/blob/dev/bug-repro/MultiThreaded/MultiThreaded.csproj) console project? I implemented the changes you suggested and wanted some additional verification before I push out another dev build

**Comment by duggaraju** [comment]
Thank you very much. This is working great. I have been at it for some time and was unable to repro the issue.

**Comment by daningalla** [comment]
Excellent - will close this and push to NuGet.
