### ISSUE TITLE
Exception while doing backing log writing.

### ISSUE THREAD

**Issue by duggaraju** [verticalsoftware/vertical-spectreconsolelogger#27]
The collection has been marked as complete with regards to additions.

   at System.Collections.Concurrent.BlockingCollection`1.TryAddWithNoTimeValidation(T item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Vertical.SpectreLogger.Output.BackgroundConsoleWriter.ResetLine()
   at Vertical.SpectreLogger.Output.WriteBuffer.Flush()
   at Vertical.SpectreLogger.Internal.WriteBufferPooledObjectPolicy.Return(IWriteBuffer obj)
   at Microsoft.Extensions.ObjectPool.DefaultObjectPool`1.Return(T obj)
   at Vertical.SpectreLogger.Rendering.RendererPipeline.Render(LogEventContext& logEventContext)
   at Vertical.SpectreLogger.SpectreLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|13_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)

Not sure how to exactly repro this other than log from multiple threads simultaneously.

**Comment by daningalla** [comment]
The background writer uses the blocking collection to buffer output to the console, and that collection gets finalized when the writer is disposed by the DI container. Items added after the writer is disposed cause that exception to be thrown. This sounds like there are threads that are still logging after the service provider is disposed.

Do you think the library should simply swallow those?

**Comment by daningalla** [comment]
I'm going to close this for now. Feel free to re-open the conversation regarding how the library should handle this.
